name: Benchmark

on: 
  pull_request:
    branches:
        - og-develop

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  profiling:
    runs-on: [self-hosted, linux, gpu]
    container:
      image: stanfordvl/omnigibson-dev:latest
      options: --gpus=all --privileged --user=root
      env:
        DISPLAY: ""
        OMNIGIBSON_HEADLESS: 1
      volumes:
        - /scr/omni-data/datasets:/data
        - /usr/share/vulkan/icd.d/nvidia_icd.json:/etc/vulkan/icd.d/nvidia_icd.json
        - /usr/share/vulkan/icd.d/nvidia_layers.json:/etc/vulkan/implicit_layer.d/nvidia_layers.json
        - /usr/share/glvnd/egl_vendor.d/10_nvidia.json:/usr/share/glvnd/egl_vendor.d/10_nvidia.json
        - /scr/omni-data/isaac-sim/cache/ov:/root/.cache/ov:rw
        - /scr/omni-data/isaac-sim/cache/pip:/root/.cache/pip:rw
        - /scr/omni-data/isaac-sim/cache/glcache:/root/.cache/nvidia/GLCache:rw
        - /scr/omni-data/isaac-sim/cache/computecache:/root/.nv/ComputeCache:rw
        - /scr/omni-data/isaac-sim/logs:/root/.nvidia-omniverse/logs:rw
        - /scr/omni-data/isaac-sim/config:/root/.nvidia-omniverse/config:rw
        - /scr/omni-data/isaac-sim/data:/root/.local/share/ov/data:rw
        - /scr/omni-data/isaac-sim/documents:/root/Documents:rw

    defaults:
      run:
        shell: micromamba run -n omnigibson /bin/bash -leo pipefail {0}

    steps:
      - name: Fix home
        run: echo "HOME=/root" >> $GITHUB_ENV

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Install
        run: pip install -e .
      
      - name: Run performance benchmark
        run: source /isaac-sim/setup_conda_env.sh && bash scripts/benchmark.sh
          
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'customSmallerIsBetter'
          output-file-path: output.json
          benchmark-data-dir-path: benchmark
          fail-on-alert: true
          alert-threshold: '200%'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          auto-push: true
